services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://database:3306/tech_shop
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tech_shop
    volumes:
      - ./tech_shop_database.sql:/docker-entrypoint-initdb.d/init.sql
